### ISSUE TITLE
Add colors to output

### ISSUE THREAD

**Issue by panglesd** [panglesd/diffcessible#5] opened 2024-02-22 10:19 UTC
Even if they are not visible by everyone, colors help to read a diff.

It would be nice to add green and red background colors to the added and removed lines, in the output.

**Comment by ademolaomosanya** [comment] 2024-03-04 16:58
hello i'm an outreachy applicant and i would love to work on this task i already have the repo running on my local machine

**Comment by yokurang** [comment] 2024-03-04 17:38
Hi, I have a fork of the machine on locally and would love to implement this feature. Here is the screenshot as requested: 
![image](https://github.com/panglesd/diffcessible/assets/114996150/5e31c2ee-798c-421b-b25c-b4a868990d7d)

**Comment by Julow** [comment] 2024-03-04 17:42
Hi @ademolaomosanya,

Thanks for your enthusiasm and congrat for having everything setup :)

The issue is your's. Hunks are currently printed using the `Patch` library's printing function, called [from here](https://github.com/panglesd/diffcessible/blob/3d2cc0eb3373fc06b2651fc4d25c1822ba2877de/lib/interactive_viewer.ml#L13).

To be able to add colors, you might need to rewrite this function, in interactive_viewer.ml, and then add the colors.
Modifying the `Patch` library for this is not the best solution as the library is intended to be used for other purpose, while colors are only useful in this project.

**Comment by Julow** [comment] 2024-03-04 17:43
Hi @yokurang,

This issue have been assigned just before you requested it. Is here an other issue that would interest you ?
I can suggest this one, for improving the status bar: https://github.com/panglesd/diffcessible/issues/18

**Comment by JeanFelixHAKIZIMANA** [comment] 2024-03-08 13:20
can you suggest me another issue other than this one please?

**Comment by Siddhi-agg** [comment] 2024-03-10 23:05
Hi @ademolaomosanya! I noticed you have been inactive for a while, so are you still working on this issue?

**Comment by maha-sachin** [comment] 2024-03-11 02:18
@Julow, I've completed the implementation for issue #17 "Compute and display number of added and removed lines in status bar" , if @ademolaomosanya is unavailable, could you assign this issue to me for further enhancements?

**Comment by Julow** [comment] 2024-03-11 09:58
@Siddhi-agg @JeanFelixHAKIZIMANA Sorry, the project was more popular than we expected and are running out of issues. Unfortunately, we are not assigning new contributors :/

@maha-sachin I do not wish to unassign an issue so fast. Let's review #17 and see what's the next best step.

**Comment by maha-sachin** [comment] 2024-03-11 12:48
> @Siddhi-agg @JeanFelixHAKIZIMANA Sorry, the project was more popular than we expected and are running out of issues. Unfortunately, we are not assigning new contributors :/
> 
> @maha-sachin I do not wish to unassign an issue so fast. Let's review #17 and see what's the next best step.

@Julow,  I appreciate your input. I agree that

**Comment by maha-sachin** [comment] 2024-03-13 16:41
Hi @Julow @panglesd, If @ademolaomosanya becomes unavailable, could you please consider assigning me to this issue? I'm keen to contribute and would be happy to take on the task.

**Comment by Julow** [comment] 2024-03-14 10:00
@ademolaomosanya Are you still interested in this issue ?

**Comment by panglesd** [comment] 2024-03-18 12:25
@ademolaomosanya are you still interested in this issue? If yes, **please open a PR by Wednesday** (or reach out to us!), otherwise we will assign this issue to someone else. However, we will only assign good first issues (such as this one) to new contributors.

**Comment by JeanFelixHAKIZIMANA** [comment] 2024-03-18 12:43
@panglesd i am ready whenever this issue becomes available, please assign it to me!

**Comment by ademolaomosanya** [comment] 2024-03-18 15:02
> @ademolaomosanya are you still interested in this issue? If yes, **please open a PR by Wednesday** (or reach out to us!), otherwise we will assign this issue to someone else. However, we will only assign good first issues (such as this one) to new contributors.

thanks @panglesd i'm very much interested in the issue i would raise a pr before wednesday

**Comment by panglesd** [comment] 2024-03-18 15:20
@JeanFelixHAKIZIMANA I have opened #44 which is very similar, feel free to request it (with a screenshot showing that you can build the project!)

**Comment by yokurang** [comment] 2024-05-19 09:37
@Julow @panglesd Please see https://github.com/panglesd/diffcessible/pull/57

**Comment by Julow** [comment] 2024-05-30 08:58
#57 is merged!

**Closed as completed by Julow** 2024-05-30 08:58 UTC
Labels: good first issue
