### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#10] opened 2024-02-22 10:35 UTC
It would be useful to have a status bar showing contextual information, for example:
- Name of the file being viewed.
- Index of the current hunk.
- Total number of hunks.

**Comment by panglesd** [comment] 2024-02-29 14:02
Duplicate of #17 and #18. Also, the "current hunk" currently does not make sense!

**Closed by panglesd** 2024-02-29 14:02 UTC
Labels: good first issue
